spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.enable_lazy_load_no_trans: true
  activemq:
    broker-url: vm://localhost
    user: thing
    password: secret

server:
  servlet.context-path: /api
  port: 5000

jms:
  queue:
    thing:
      create: thing.create
      update: thing.update
      created: thing.created
      changed: thing.changed
    message:
      received: message.received
